// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: testproto.proto

package testproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestStatus int32

const (
	TestStatus_UNKNOWN TestStatus = 0
	TestStatus_PENDING TestStatus = 1
	TestStatus_ACTIVE  TestStatus = 2
)

// Enum value maps for TestStatus.
var (
	TestStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "ACTIVE",
	}
	TestStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"PENDING": 1,
		"ACTIVE":  2,
	}
)

func (x TestStatus) Enum() *TestStatus {
	p := new(TestStatus)
	*p = x
	return p
}

func (x TestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_testproto_proto_enumTypes[0].Descriptor()
}

func (TestStatus) Type() protoreflect.EnumType {
	return &file_testproto_proto_enumTypes[0]
}

func (x TestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestStatus.Descriptor instead.
func (TestStatus) EnumDescriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{0}
}

type DeepMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leaf          string                 `protobuf:"bytes,1,opt,name=leaf,proto3" json:"leaf,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeepMsg) Reset() {
	*x = DeepMsg{}
	mi := &file_testproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepMsg) ProtoMessage() {}

func (x *DeepMsg) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeepMsg.ProtoReflect.Descriptor instead.
func (*DeepMsg) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{0}
}

func (x *DeepMsg) GetLeaf() string {
	if x != nil {
		return x.Leaf
	}
	return ""
}

type NestedMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Count int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Deep  *DeepMsg               `protobuf:"bytes,3,opt,name=deep,proto3" json:"deep,omitempty"`
	Attrs map[string]string      `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// parts intentionally uses field number 10, the same as TestMsg.items, to
	// exercise that the flattener's per-call fieldArrays scoping correctly
	// isolates array ID allocation at each nesting level.
	Parts         []*DeepMsg `protobuf:"bytes,10,rep,name=parts,proto3" json:"parts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMsg) Reset() {
	*x = NestedMsg{}
	mi := &file_testproto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMsg) ProtoMessage() {}

func (x *NestedMsg) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMsg.ProtoReflect.Descriptor instead.
func (*NestedMsg) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{1}
}

func (x *NestedMsg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NestedMsg) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *NestedMsg) GetDeep() *DeepMsg {
	if x != nil {
		return x.Deep
	}
	return nil
}

func (x *NestedMsg) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *NestedMsg) GetParts() []*DeepMsg {
	if x != nil {
		return x.Parts
	}
	return nil
}

type TestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Flag          bool                   `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	Ratio         float64                `protobuf:"fixed64,5,opt,name=ratio,proto3" json:"ratio,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Status        TestStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=test.TestStatus" json:"status,omitempty"`
	Nested        *NestedMsg             `protobuf:"bytes,8,opt,name=nested,proto3" json:"nested,omitempty"`
	Tags          []int32                `protobuf:"varint,9,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	Items         []*NestedMsg           `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SignedVal     int32                  `protobuf:"zigzag32,12,opt,name=signed_val,json=signedVal,proto3" json:"signed_val,omitempty"`
	Big           uint64                 `protobuf:"varint,13,opt,name=big,proto3" json:"big,omitempty"`
	Sf32          int32                  `protobuf:"fixed32,14,opt,name=sf32,proto3" json:"sf32,omitempty"`
	Sf64          int64                  `protobuf:"fixed64,15,opt,name=sf64,proto3" json:"sf64,omitempty"`
	F32           uint32                 `protobuf:"fixed32,16,opt,name=f32,proto3" json:"f32,omitempty"`
	F64           uint64                 `protobuf:"fixed64,17,opt,name=f64,proto3" json:"f64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMsg) Reset() {
	*x = TestMsg{}
	mi := &file_testproto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMsg) ProtoMessage() {}

func (x *TestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_testproto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMsg.ProtoReflect.Descriptor instead.
func (*TestMsg) Descriptor() ([]byte, []int) {
	return file_testproto_proto_rawDescGZIP(), []int{2}
}

func (x *TestMsg) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMsg) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *TestMsg) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TestMsg) GetRatio() float64 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *TestMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TestMsg) GetStatus() TestStatus {
	if x != nil {
		return x.Status
	}
	return TestStatus_UNKNOWN
}

func (x *TestMsg) GetNested() *NestedMsg {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *TestMsg) GetTags() []int32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *TestMsg) GetItems() []*NestedMsg {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *TestMsg) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TestMsg) GetSignedVal() int32 {
	if x != nil {
		return x.SignedVal
	}
	return 0
}

func (x *TestMsg) GetBig() uint64 {
	if x != nil {
		return x.Big
	}
	return 0
}

func (x *TestMsg) GetSf32() int32 {
	if x != nil {
		return x.Sf32
	}
	return 0
}

func (x *TestMsg) GetSf64() int64 {
	if x != nil {
		return x.Sf64
	}
	return 0
}

func (x *TestMsg) GetF32() uint32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *TestMsg) GetF64() uint64 {
	if x != nil {
		return x.F64
	}
	return 0
}

var File_testproto_proto protoreflect.FileDescriptor

const file_testproto_proto_rawDesc = "" +
	"\n" +
	"\x0ftestproto.proto\x12\x04test\"\x1d\n" +
	"\aDeepMsg\x12\x12\n" +
	"\x04leaf\x18\x01 \x01(\tR\x04leaf\"\xeb\x01\n" +
	"\tNestedMsg\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12!\n" +
	"\x04deep\x18\x03 \x01(\v2\r.test.DeepMsgR\x04deep\x120\n" +
	"\x05attrs\x18\x04 \x03(\v2\x1a.test.NestedMsg.AttrsEntryR\x05attrs\x12#\n" +
	"\x05parts\x18\n" +
	" \x03(\v2\r.test.DeepMsgR\x05parts\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x03\n" +
	"\aTestMsg\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\bR\x04flag\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\x12\x14\n" +
	"\x05ratio\x18\x05 \x01(\x01R\x05ratio\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.test.TestStatusR\x06status\x12'\n" +
	"\x06nested\x18\b \x01(\v2\x0f.test.NestedMsgR\x06nested\x12\x12\n" +
	"\x04tags\x18\t \x03(\x05R\x04tags\x12%\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x0f.test.NestedMsgR\x05items\x121\n" +
	"\x06labels\x18\v \x03(\v2\x19.test.TestMsg.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"signed_val\x18\f \x01(\x11R\tsignedVal\x12\x10\n" +
	"\x03big\x18\r \x01(\x04R\x03big\x12\x12\n" +
	"\x04sf32\x18\x0e \x01(\x0fR\x04sf32\x12\x12\n" +
	"\x04sf64\x18\x0f \x01(\x10R\x04sf64\x12\x10\n" +
	"\x03f32\x18\x10 \x01(\aR\x03f32\x12\x10\n" +
	"\x03f64\x18\x11 \x01(\x06R\x03f64\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*2\n" +
	"\n" +
	"TestStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x02B9Z7github.com/spenczar/quamina-protobuf/internal/testprotob\x06proto3"

var (
	file_testproto_proto_rawDescOnce sync.Once
	file_testproto_proto_rawDescData []byte
)

func file_testproto_proto_rawDescGZIP() []byte {
	file_testproto_proto_rawDescOnce.Do(func() {
		file_testproto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testproto_proto_rawDesc), len(file_testproto_proto_rawDesc)))
	})
	return file_testproto_proto_rawDescData
}

var file_testproto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testproto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_testproto_proto_goTypes = []any{
	(TestStatus)(0),   // 0: test.TestStatus
	(*DeepMsg)(nil),   // 1: test.DeepMsg
	(*NestedMsg)(nil), // 2: test.NestedMsg
	(*TestMsg)(nil),   // 3: test.TestMsg
	nil,               // 4: test.NestedMsg.AttrsEntry
	nil,               // 5: test.TestMsg.LabelsEntry
}
var file_testproto_proto_depIdxs = []int32{
	1, // 0: test.NestedMsg.deep:type_name -> test.DeepMsg
	4, // 1: test.NestedMsg.attrs:type_name -> test.NestedMsg.AttrsEntry
	1, // 2: test.NestedMsg.parts:type_name -> test.DeepMsg
	0, // 3: test.TestMsg.status:type_name -> test.TestStatus
	2, // 4: test.TestMsg.nested:type_name -> test.NestedMsg
	2, // 5: test.TestMsg.items:type_name -> test.NestedMsg
	5, // 6: test.TestMsg.labels:type_name -> test.TestMsg.LabelsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_testproto_proto_init() }
func file_testproto_proto_init() {
	if File_testproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testproto_proto_rawDesc), len(file_testproto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testproto_proto_goTypes,
		DependencyIndexes: file_testproto_proto_depIdxs,
		EnumInfos:         file_testproto_proto_enumTypes,
		MessageInfos:      file_testproto_proto_msgTypes,
	}.Build()
	File_testproto_proto = out.File
	file_testproto_proto_goTypes = nil
	file_testproto_proto_depIdxs = nil
}
